"""Initial schema

Revision ID: cb29296e02db
Revises: 
Create Date: 2026-07-12 11:33:59.627090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb29296e02db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farmer_materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_farmer_materials_item_code'), ['item_code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farmer_materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_farmer_materials_item_code'))

    # ### end Alembic commands ###
